"""Public primitives for the Atlas N+1 acceptance evidence harness."""

from atlas.acceptance.anti_self import (
    CanonicalIndependentWitnessRequirement,
    CanonicalVerifierMismatchError,
    ContractIdentityMismatchError,
    IndependentWitnessBinding,
    IndependentWitnessClaim,
    IndependentWitnessClassError,
    IndependentWitnessValidationError,
    IndependentWitnessValidator,
    MaterialActorMismatchError,
    SelfVerifierError,
)
from atlas.acceptance.core import (
    AcceptanceContract,
    AcceptanceContractRegistry,
    AcceptanceEvidenceReceipt,
    AcceptanceLevel,
    AcceptanceLevelMismatchError,
    AcceptanceResult,
    BoundAcceptanceEvidence,
    ContractProvenance,
    DuplicateAcceptanceContractError,
    EvidenceLocator,
    IndependenceClass,
    ReceiptEnvelopeAdapter,
    TimestampOrder,
    UnknownAcceptanceContractError,
)
from atlas.acceptance.identity import (
    DuplicateVerifierIdentityError,
    TrustDomainComparison,
    UnknownVerifierIdentityError,
    VerifierIdentityMetadata,
    VerifierIdentityRegistry,
)
from atlas.acceptance.receipts import (
    CapturedAcceptanceReceipt,
    RECEIPT_RETENTION_METADATA,
    ReceiptCaptureAdapter,
)

__all__ = [
    "AcceptanceContract",
    "AcceptanceContractRegistry",
    "AcceptanceEvidenceReceipt",
    "AcceptanceLevel",
    "AcceptanceLevelMismatchError",
    "AcceptanceResult",
    "BoundAcceptanceEvidence",
    "CapturedAcceptanceReceipt",
    "CanonicalIndependentWitnessRequirement",
    "CanonicalVerifierMismatchError",
    "ContractProvenance",
    "ContractIdentityMismatchError",
    "DuplicateAcceptanceContractError",
    "DuplicateVerifierIdentityError",
    "EvidenceLocator",
    "IndependenceClass",
    "IndependentWitnessBinding",
    "IndependentWitnessClaim",
    "IndependentWitnessClassError",
    "IndependentWitnessValidationError",
    "IndependentWitnessValidator",
    "MaterialActorMismatchError",
    "ReceiptEnvelopeAdapter",
    "RECEIPT_RETENTION_METADATA",
    "ReceiptCaptureAdapter",
    "TimestampOrder",
    "SelfVerifierError",
    "TrustDomainComparison",
    "UnknownAcceptanceContractError",
    "UnknownVerifierIdentityError",
    "VerifierIdentityMetadata",
    "VerifierIdentityRegistry",
]
